# Yarn Berry config.
# IMPORTANT: The user requested node_modules linking (not PnP).
nodeLinker: node-modules

# If you use Corepack (recommended), you do NOT need to commit a yarnPath.
# yarnPath: .yarn/releases/yarn-4.6.0.cjs
